
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: info

config:

discovery:


alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.ca
      

hacs:
  token: e500b47d19e4d5837f9972bc1ce5fef3942a697f
  

# Multiple recipients
notify:
  - platform: clicksend
    name: ClickSend
    username: djkumar72
    api_key: !secret clicksend_apikey
    recipient: [6474096487, 4168322003]

panel_custom: !include panel_custom.yaml

alarm_control_panel: !include resources/bwalarm/bwalarm.yaml



konnected:
  access_token: JayKonnected
  devices:
    - id: cc50e35d1e8e
      binary_sensors:
        - zone: 1
          type: door
          name: "Patio Door"
        - zone: 2
          type: door
          name: "Entrance Doors"