
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

config:

discovery:

panel_custom:
  - name: hassio-main
    sidebar_title: Configurator
    sidebar_icon: mdi:wrench
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: "core_configurator"

konnected:
  access_token: JayKonnected
  devices:
    - id: cc50e35d1e8e
      binary_sensors:
        - zone: 1
          type: door
          name: "Patio Door"
        - zone: 2
          type: door
          name: "Entrance Doors"